/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.innoventionist.artham;

public final class R {
  public static final class anim {
    public static final int fab_scale_down=0x7f010000;
    public static final int fab_scale_up=0x7f010001;
    public static final int fab_slide_in_from_left=0x7f010002;
    public static final int fab_slide_in_from_right=0x7f010003;
    public static final int fab_slide_out_to_left=0x7f010004;
    public static final int fab_slide_out_to_right=0x7f010005;
  }
  public static final class attr {
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int cardShape=0x7f020000;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int dividerColor=0x7f020001;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int fab_colorDisabled=0x7f020002;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int fab_colorNormal=0x7f020003;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int fab_colorPressed=0x7f020004;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int fab_colorRipple=0x7f020005;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int fab_elevationCompat=0x7f020006;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int fab_hideAnimation=0x7f020007;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int fab_label=0x7f020008;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int fab_progress=0x7f020009;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int fab_progress_backgroundColor=0x7f02000a;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int fab_progress_color=0x7f02000b;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int fab_progress_indeterminate=0x7f02000c;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int fab_progress_max=0x7f02000d;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int fab_progress_showBackground=0x7f02000e;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int fab_shadowColor=0x7f02000f;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int fab_shadowRadius=0x7f020010;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int fab_shadowXOffset=0x7f020011;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int fab_shadowYOffset=0x7f020012;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int fab_showAnimation=0x7f020013;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int fab_showShadow=0x7f020014;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>mini</td><td>1</td><td></td></tr>
     * <tr><td>normal</td><td>0</td><td></td></tr>
     * </table>
     */
    public static final int fab_size=0x7f020015;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int menu_animationDelayPerItem=0x7f020016;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_backgroundColor=0x7f020017;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_buttonSpacing=0x7f020018;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int menu_buttonToggleAnimation=0x7f020019;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_colorNormal=0x7f02001a;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_colorPressed=0x7f02001b;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_colorRipple=0x7f02001c;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int menu_fab_hide_animation=0x7f02001d;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int menu_fab_label=0x7f02001e;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int menu_fab_show_animation=0x7f02001f;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>mini</td><td>1</td><td></td></tr>
     * <tr><td>normal</td><td>0</td><td></td></tr>
     * </table>
     */
    public static final int menu_fab_size=0x7f020020;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int menu_icon=0x7f020021;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_labels_colorNormal=0x7f020022;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_labels_colorPressed=0x7f020023;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_labels_colorRipple=0x7f020024;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_labels_cornerRadius=0x7f020025;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int menu_labels_customFont=0x7f020026;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>end</td><td>3</td><td></td></tr>
     * <tr><td>marquee</td><td>4</td><td></td></tr>
     * <tr><td>middle</td><td>2</td><td></td></tr>
     * <tr><td>none</td><td>0</td><td></td></tr>
     * <tr><td>start</td><td>1</td><td></td></tr>
     * </table>
     */
    public static final int menu_labels_ellipsize=0x7f020027;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int menu_labels_hideAnimation=0x7f020028;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_labels_margin=0x7f020029;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int menu_labels_maxLines=0x7f02002a;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_labels_padding=0x7f02002b;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_labels_paddingBottom=0x7f02002c;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_labels_paddingLeft=0x7f02002d;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_labels_paddingRight=0x7f02002e;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_labels_paddingTop=0x7f02002f;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>left</td><td>0</td><td></td></tr>
     * <tr><td>right</td><td>1</td><td></td></tr>
     * </table>
     */
    public static final int menu_labels_position=0x7f020030;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int menu_labels_showAnimation=0x7f020031;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int menu_labels_showShadow=0x7f020032;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int menu_labels_singleLine=0x7f020033;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int menu_labels_style=0x7f020034;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_labels_textColor=0x7f020035;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_labels_textSize=0x7f020036;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>down</td><td>1</td><td></td></tr>
     * <tr><td>up</td><td>0</td><td></td></tr>
     * </table>
     */
    public static final int menu_openDirection=0x7f020037;
    /**
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     */
    public static final int menu_shadowColor=0x7f020038;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_shadowRadius=0x7f020039;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_shadowXOffset=0x7f02003a;
    /**
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     */
    public static final int menu_shadowYOffset=0x7f02003b;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int menu_showShadow=0x7f02003c;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int textColor=0x7f02003d;
  }
  public static final class color {
    public static final int darkDivider=0x7f030000;
    public static final int darkText=0x7f030001;
    public static final int lightDivider=0x7f030002;
    public static final int lightText=0x7f030003;
  }
  public static final class dimen {
    /**
     * Default screen margins, per the Android Design guidelines.
     */
    public static final int activity_horizontal_margin=0x7f040000;
    public static final int activity_vertical_margin=0x7f040001;
    public static final int fab_size_mini=0x7f040002;
    public static final int fab_size_normal=0x7f040003;
    public static final int labels_text_size=0x7f040004;
  }
  public static final class drawable {
    public static final int artham=0x7f050000;
    public static final int bookmark_false=0x7f050001;
    public static final int bookmark_true=0x7f050002;
    public static final int clear=0x7f050003;
    public static final int cursor=0x7f050004;
    public static final int delete=0x7f050005;
    public static final int fav=0x7f050006;
    public static final int info=0x7f050007;
    public static final int link=0x7f050008;
    public static final int mic=0x7f050009;
    public static final int more=0x7f05000a;
    public static final int search=0x7f05000b;
    public static final int settings=0x7f05000c;
    public static final int shape=0x7f05000d;
    public static final int shape_dark=0x7f05000e;
    public static final int share=0x7f05000f;
    public static final int speak=0x7f050010;
    public static final int star=0x7f050011;
    public static final int theme=0x7f050012;
  }
  public static final class id {
    public static final int bookmarkButton=0x7f060000;
    public static final int bookmarksListView=0x7f060001;
    public static final int bookmarksTitle=0x7f060002;
    public static final int clearHistory=0x7f060003;
    public static final int clearquery=0x7f060004;
    public static final int down=0x7f060005;
    public static final int end=0x7f060006;
    public static final int fab_label=0x7f060007;
    public static final int left=0x7f060008;
    public static final int listitem=0x7f060009;
    public static final int mainlayout=0x7f06000a;
    public static final int marquee=0x7f06000b;
    public static final int material_design_android_floating_action_menu=0x7f06000c;
    public static final int meaningView=0x7f06000d;
    public static final int meaningsContainer=0x7f06000e;
    public static final int meaningsTitle=0x7f06000f;
    public static final int middle=0x7f060010;
    public static final int mini=0x7f060011;
    public static final int none=0x7f060012;
    public static final int normal=0x7f060013;
    public static final int rate_app=0x7f060014;
    public static final int recentsContainer=0x7f060015;
    public static final int recentsListView=0x7f060016;
    public static final int recentsTitle=0x7f060017;
    public static final int right=0x7f060018;
    public static final int searchIcon=0x7f060019;
    public static final int searchView=0x7f06001a;
    public static final int searchwraper=0x7f06001b;
    public static final int share_app=0x7f06001c;
    public static final int speak=0x7f06001d;
    public static final int start=0x7f06001e;
    public static final int statusBar=0x7f06001f;
    public static final int suggestionsContainer=0x7f060020;
    public static final int suggestionsListView=0x7f060021;
    public static final int suggestionsTitle=0x7f060022;
    public static final int title=0x7f060023;
    public static final int toggle_theme=0x7f060024;
    public static final int up=0x7f060025;
    public static final int visit_website=0x7f060026;
    public static final int voice=0x7f060027;
  }
  public static final class layout {
    public static final int activity_main=0x7f070000;
    public static final int listitem=0x7f070001;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f080000;
  }
  public static final class raw {
    public static final int mdb=0x7f090000;
    public static final int wdbd=0x7f090001;
  }
  public static final class string {
    public static final int app_name=0x7f0a0000;
  }
  public static final class style {
    public static final int AppThemeDark=0x7f0b0000;
    public static final int AppThemeLight=0x7f0b0001;
  }
  public static final class styleable {
    /**
     * Attributes that can be used with a FloatingActionButton.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_colorDisabled com.innoventionist.artham:fab_colorDisabled}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_colorNormal com.innoventionist.artham:fab_colorNormal}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_colorPressed com.innoventionist.artham:fab_colorPressed}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_colorRipple com.innoventionist.artham:fab_colorRipple}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_elevationCompat com.innoventionist.artham:fab_elevationCompat}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_hideAnimation com.innoventionist.artham:fab_hideAnimation}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_label com.innoventionist.artham:fab_label}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_progress com.innoventionist.artham:fab_progress}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_progress_backgroundColor com.innoventionist.artham:fab_progress_backgroundColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_progress_color com.innoventionist.artham:fab_progress_color}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_progress_indeterminate com.innoventionist.artham:fab_progress_indeterminate}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_progress_max com.innoventionist.artham:fab_progress_max}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_progress_showBackground com.innoventionist.artham:fab_progress_showBackground}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_shadowColor com.innoventionist.artham:fab_shadowColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_shadowRadius com.innoventionist.artham:fab_shadowRadius}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_shadowXOffset com.innoventionist.artham:fab_shadowXOffset}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_shadowYOffset com.innoventionist.artham:fab_shadowYOffset}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_showAnimation com.innoventionist.artham:fab_showAnimation}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_showShadow com.innoventionist.artham:fab_showShadow}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionButton_fab_size com.innoventionist.artham:fab_size}</code></td><td></td></tr>
     * </table>
     * @see #FloatingActionButton_fab_colorDisabled
     * @see #FloatingActionButton_fab_colorNormal
     * @see #FloatingActionButton_fab_colorPressed
     * @see #FloatingActionButton_fab_colorRipple
     * @see #FloatingActionButton_fab_elevationCompat
     * @see #FloatingActionButton_fab_hideAnimation
     * @see #FloatingActionButton_fab_label
     * @see #FloatingActionButton_fab_progress
     * @see #FloatingActionButton_fab_progress_backgroundColor
     * @see #FloatingActionButton_fab_progress_color
     * @see #FloatingActionButton_fab_progress_indeterminate
     * @see #FloatingActionButton_fab_progress_max
     * @see #FloatingActionButton_fab_progress_showBackground
     * @see #FloatingActionButton_fab_shadowColor
     * @see #FloatingActionButton_fab_shadowRadius
     * @see #FloatingActionButton_fab_shadowXOffset
     * @see #FloatingActionButton_fab_shadowYOffset
     * @see #FloatingActionButton_fab_showAnimation
     * @see #FloatingActionButton_fab_showShadow
     * @see #FloatingActionButton_fab_size
     */
    public static final int[] FloatingActionButton={
      0x7f020002, 0x7f020003, 0x7f020004, 0x7f020005, 
      0x7f020006, 0x7f020007, 0x7f020008, 0x7f020009, 
      0x7f02000a, 0x7f02000b, 0x7f02000c, 0x7f02000d, 
      0x7f02000e, 0x7f02000f, 0x7f020010, 0x7f020011, 
      0x7f020012, 0x7f020013, 0x7f020014, 0x7f020015
    };
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_colorDisabled}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_colorDisabled
     */
    public static final int FloatingActionButton_fab_colorDisabled=0;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_colorNormal}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_colorNormal
     */
    public static final int FloatingActionButton_fab_colorNormal=1;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_colorPressed}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_colorPressed
     */
    public static final int FloatingActionButton_fab_colorPressed=2;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_colorRipple}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_colorRipple
     */
    public static final int FloatingActionButton_fab_colorRipple=3;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_elevationCompat}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:fab_elevationCompat
     */
    public static final int FloatingActionButton_fab_elevationCompat=4;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_hideAnimation}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_hideAnimation
     */
    public static final int FloatingActionButton_fab_hideAnimation=5;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_label}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.innoventionist.artham:fab_label
     */
    public static final int FloatingActionButton_fab_label=6;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_progress}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.innoventionist.artham:fab_progress
     */
    public static final int FloatingActionButton_fab_progress=7;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_progress_backgroundColor}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_progress_backgroundColor
     */
    public static final int FloatingActionButton_fab_progress_backgroundColor=8;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_progress_color}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_progress_color
     */
    public static final int FloatingActionButton_fab_progress_color=9;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_progress_indeterminate}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.innoventionist.artham:fab_progress_indeterminate
     */
    public static final int FloatingActionButton_fab_progress_indeterminate=10;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_progress_max}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.innoventionist.artham:fab_progress_max
     */
    public static final int FloatingActionButton_fab_progress_max=11;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_progress_showBackground}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.innoventionist.artham:fab_progress_showBackground
     */
    public static final int FloatingActionButton_fab_progress_showBackground=12;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_shadowColor}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_shadowColor
     */
    public static final int FloatingActionButton_fab_shadowColor=13;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_shadowRadius}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:fab_shadowRadius
     */
    public static final int FloatingActionButton_fab_shadowRadius=14;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_shadowXOffset}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:fab_shadowXOffset
     */
    public static final int FloatingActionButton_fab_shadowXOffset=15;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_shadowYOffset}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:fab_shadowYOffset
     */
    public static final int FloatingActionButton_fab_shadowYOffset=16;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_showAnimation}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:fab_showAnimation
     */
    public static final int FloatingActionButton_fab_showAnimation=17;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_showShadow}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.innoventionist.artham:fab_showShadow
     */
    public static final int FloatingActionButton_fab_showShadow=18;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#fab_size}
     * attribute's value can be found in the {@link #FloatingActionButton} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>mini</td><td>1</td><td></td></tr>
     * <tr><td>normal</td><td>0</td><td></td></tr>
     * </table>
     *
     * @attr name com.innoventionist.artham:fab_size
     */
    public static final int FloatingActionButton_fab_size=19;
    /**
     * Attributes that can be used with a FloatingActionMenu.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_animationDelayPerItem com.innoventionist.artham:menu_animationDelayPerItem}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_backgroundColor com.innoventionist.artham:menu_backgroundColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_buttonSpacing com.innoventionist.artham:menu_buttonSpacing}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_buttonToggleAnimation com.innoventionist.artham:menu_buttonToggleAnimation}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_colorNormal com.innoventionist.artham:menu_colorNormal}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_colorPressed com.innoventionist.artham:menu_colorPressed}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_colorRipple com.innoventionist.artham:menu_colorRipple}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_fab_hide_animation com.innoventionist.artham:menu_fab_hide_animation}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_fab_label com.innoventionist.artham:menu_fab_label}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_fab_show_animation com.innoventionist.artham:menu_fab_show_animation}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_fab_size com.innoventionist.artham:menu_fab_size}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_icon com.innoventionist.artham:menu_icon}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_colorNormal com.innoventionist.artham:menu_labels_colorNormal}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_colorPressed com.innoventionist.artham:menu_labels_colorPressed}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_colorRipple com.innoventionist.artham:menu_labels_colorRipple}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_cornerRadius com.innoventionist.artham:menu_labels_cornerRadius}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_customFont com.innoventionist.artham:menu_labels_customFont}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_ellipsize com.innoventionist.artham:menu_labels_ellipsize}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_hideAnimation com.innoventionist.artham:menu_labels_hideAnimation}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_margin com.innoventionist.artham:menu_labels_margin}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_maxLines com.innoventionist.artham:menu_labels_maxLines}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_padding com.innoventionist.artham:menu_labels_padding}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_paddingBottom com.innoventionist.artham:menu_labels_paddingBottom}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_paddingLeft com.innoventionist.artham:menu_labels_paddingLeft}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_paddingRight com.innoventionist.artham:menu_labels_paddingRight}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_paddingTop com.innoventionist.artham:menu_labels_paddingTop}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_position com.innoventionist.artham:menu_labels_position}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_showAnimation com.innoventionist.artham:menu_labels_showAnimation}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_showShadow com.innoventionist.artham:menu_labels_showShadow}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_singleLine com.innoventionist.artham:menu_labels_singleLine}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_style com.innoventionist.artham:menu_labels_style}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_textColor com.innoventionist.artham:menu_labels_textColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_labels_textSize com.innoventionist.artham:menu_labels_textSize}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_openDirection com.innoventionist.artham:menu_openDirection}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_shadowColor com.innoventionist.artham:menu_shadowColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_shadowRadius com.innoventionist.artham:menu_shadowRadius}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_shadowXOffset com.innoventionist.artham:menu_shadowXOffset}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_shadowYOffset com.innoventionist.artham:menu_shadowYOffset}</code></td><td></td></tr>
     * <tr><td><code>{@link #FloatingActionMenu_menu_showShadow com.innoventionist.artham:menu_showShadow}</code></td><td></td></tr>
     * </table>
     * @see #FloatingActionMenu_menu_animationDelayPerItem
     * @see #FloatingActionMenu_menu_backgroundColor
     * @see #FloatingActionMenu_menu_buttonSpacing
     * @see #FloatingActionMenu_menu_buttonToggleAnimation
     * @see #FloatingActionMenu_menu_colorNormal
     * @see #FloatingActionMenu_menu_colorPressed
     * @see #FloatingActionMenu_menu_colorRipple
     * @see #FloatingActionMenu_menu_fab_hide_animation
     * @see #FloatingActionMenu_menu_fab_label
     * @see #FloatingActionMenu_menu_fab_show_animation
     * @see #FloatingActionMenu_menu_fab_size
     * @see #FloatingActionMenu_menu_icon
     * @see #FloatingActionMenu_menu_labels_colorNormal
     * @see #FloatingActionMenu_menu_labels_colorPressed
     * @see #FloatingActionMenu_menu_labels_colorRipple
     * @see #FloatingActionMenu_menu_labels_cornerRadius
     * @see #FloatingActionMenu_menu_labels_customFont
     * @see #FloatingActionMenu_menu_labels_ellipsize
     * @see #FloatingActionMenu_menu_labels_hideAnimation
     * @see #FloatingActionMenu_menu_labels_margin
     * @see #FloatingActionMenu_menu_labels_maxLines
     * @see #FloatingActionMenu_menu_labels_padding
     * @see #FloatingActionMenu_menu_labels_paddingBottom
     * @see #FloatingActionMenu_menu_labels_paddingLeft
     * @see #FloatingActionMenu_menu_labels_paddingRight
     * @see #FloatingActionMenu_menu_labels_paddingTop
     * @see #FloatingActionMenu_menu_labels_position
     * @see #FloatingActionMenu_menu_labels_showAnimation
     * @see #FloatingActionMenu_menu_labels_showShadow
     * @see #FloatingActionMenu_menu_labels_singleLine
     * @see #FloatingActionMenu_menu_labels_style
     * @see #FloatingActionMenu_menu_labels_textColor
     * @see #FloatingActionMenu_menu_labels_textSize
     * @see #FloatingActionMenu_menu_openDirection
     * @see #FloatingActionMenu_menu_shadowColor
     * @see #FloatingActionMenu_menu_shadowRadius
     * @see #FloatingActionMenu_menu_shadowXOffset
     * @see #FloatingActionMenu_menu_shadowYOffset
     * @see #FloatingActionMenu_menu_showShadow
     */
    public static final int[] FloatingActionMenu={
      0x7f020016, 0x7f020017, 0x7f020018, 0x7f020019, 
      0x7f02001a, 0x7f02001b, 0x7f02001c, 0x7f02001d, 
      0x7f02001e, 0x7f02001f, 0x7f020020, 0x7f020021, 
      0x7f020022, 0x7f020023, 0x7f020024, 0x7f020025, 
      0x7f020026, 0x7f020027, 0x7f020028, 0x7f020029, 
      0x7f02002a, 0x7f02002b, 0x7f02002c, 0x7f02002d, 
      0x7f02002e, 0x7f02002f, 0x7f020030, 0x7f020031, 
      0x7f020032, 0x7f020033, 0x7f020034, 0x7f020035, 
      0x7f020036, 0x7f020037, 0x7f020038, 0x7f020039, 
      0x7f02003a, 0x7f02003b, 0x7f02003c
    };
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_animationDelayPerItem}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.innoventionist.artham:menu_animationDelayPerItem
     */
    public static final int FloatingActionMenu_menu_animationDelayPerItem=0;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_backgroundColor}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_backgroundColor
     */
    public static final int FloatingActionMenu_menu_backgroundColor=1;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_buttonSpacing}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_buttonSpacing
     */
    public static final int FloatingActionMenu_menu_buttonSpacing=2;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_buttonToggleAnimation}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_buttonToggleAnimation
     */
    public static final int FloatingActionMenu_menu_buttonToggleAnimation=3;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_colorNormal}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_colorNormal
     */
    public static final int FloatingActionMenu_menu_colorNormal=4;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_colorPressed}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_colorPressed
     */
    public static final int FloatingActionMenu_menu_colorPressed=5;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_colorRipple}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_colorRipple
     */
    public static final int FloatingActionMenu_menu_colorRipple=6;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_fab_hide_animation}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_fab_hide_animation
     */
    public static final int FloatingActionMenu_menu_fab_hide_animation=7;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_fab_label}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.innoventionist.artham:menu_fab_label
     */
    public static final int FloatingActionMenu_menu_fab_label=8;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_fab_show_animation}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_fab_show_animation
     */
    public static final int FloatingActionMenu_menu_fab_show_animation=9;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_fab_size}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>mini</td><td>1</td><td></td></tr>
     * <tr><td>normal</td><td>0</td><td></td></tr>
     * </table>
     *
     * @attr name com.innoventionist.artham:menu_fab_size
     */
    public static final int FloatingActionMenu_menu_fab_size=10;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_icon}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_icon
     */
    public static final int FloatingActionMenu_menu_icon=11;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_colorNormal}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_colorNormal
     */
    public static final int FloatingActionMenu_menu_labels_colorNormal=12;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_colorPressed}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_colorPressed
     */
    public static final int FloatingActionMenu_menu_labels_colorPressed=13;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_colorRipple}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_colorRipple
     */
    public static final int FloatingActionMenu_menu_labels_colorRipple=14;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_cornerRadius}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_labels_cornerRadius
     */
    public static final int FloatingActionMenu_menu_labels_cornerRadius=15;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_customFont}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.innoventionist.artham:menu_labels_customFont
     */
    public static final int FloatingActionMenu_menu_labels_customFont=16;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_ellipsize}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>end</td><td>3</td><td></td></tr>
     * <tr><td>marquee</td><td>4</td><td></td></tr>
     * <tr><td>middle</td><td>2</td><td></td></tr>
     * <tr><td>none</td><td>0</td><td></td></tr>
     * <tr><td>start</td><td>1</td><td></td></tr>
     * </table>
     *
     * @attr name com.innoventionist.artham:menu_labels_ellipsize
     */
    public static final int FloatingActionMenu_menu_labels_ellipsize=17;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_hideAnimation}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_hideAnimation
     */
    public static final int FloatingActionMenu_menu_labels_hideAnimation=18;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_margin}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_labels_margin
     */
    public static final int FloatingActionMenu_menu_labels_margin=19;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_maxLines}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_maxLines
     */
    public static final int FloatingActionMenu_menu_labels_maxLines=20;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_padding}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_labels_padding
     */
    public static final int FloatingActionMenu_menu_labels_padding=21;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_paddingBottom}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_labels_paddingBottom
     */
    public static final int FloatingActionMenu_menu_labels_paddingBottom=22;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_paddingLeft}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_labels_paddingLeft
     */
    public static final int FloatingActionMenu_menu_labels_paddingLeft=23;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_paddingRight}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_labels_paddingRight
     */
    public static final int FloatingActionMenu_menu_labels_paddingRight=24;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_paddingTop}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_labels_paddingTop
     */
    public static final int FloatingActionMenu_menu_labels_paddingTop=25;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_position}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>left</td><td>0</td><td></td></tr>
     * <tr><td>right</td><td>1</td><td></td></tr>
     * </table>
     *
     * @attr name com.innoventionist.artham:menu_labels_position
     */
    public static final int FloatingActionMenu_menu_labels_position=26;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_showAnimation}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_showAnimation
     */
    public static final int FloatingActionMenu_menu_labels_showAnimation=27;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_showShadow}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_showShadow
     */
    public static final int FloatingActionMenu_menu_labels_showShadow=28;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_singleLine}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_singleLine
     */
    public static final int FloatingActionMenu_menu_labels_singleLine=29;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_style}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_style
     */
    public static final int FloatingActionMenu_menu_labels_style=30;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_textColor}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_labels_textColor
     */
    public static final int FloatingActionMenu_menu_labels_textColor=31;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_labels_textSize}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_labels_textSize
     */
    public static final int FloatingActionMenu_menu_labels_textSize=32;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_openDirection}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>down</td><td>1</td><td></td></tr>
     * <tr><td>up</td><td>0</td><td></td></tr>
     * </table>
     *
     * @attr name com.innoventionist.artham:menu_openDirection
     */
    public static final int FloatingActionMenu_menu_openDirection=33;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_shadowColor}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name com.innoventionist.artham:menu_shadowColor
     */
    public static final int FloatingActionMenu_menu_shadowColor=34;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_shadowRadius}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_shadowRadius
     */
    public static final int FloatingActionMenu_menu_shadowRadius=35;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_shadowXOffset}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_shadowXOffset
     */
    public static final int FloatingActionMenu_menu_shadowXOffset=36;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_shadowYOffset}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     *
     * @attr name com.innoventionist.artham:menu_shadowYOffset
     */
    public static final int FloatingActionMenu_menu_shadowYOffset=37;
    /**
     * <p>This symbol is the offset where the {@link com.innoventionist.artham.R.attr#menu_showShadow}
     * attribute's value can be found in the {@link #FloatingActionMenu} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.innoventionist.artham:menu_showShadow
     */
    public static final int FloatingActionMenu_menu_showShadow=38;
  }
}